runtime: nodejs18
instance_class: F2
env_variables:
  PUBLIC_CLOUDINARY_API_KEY: "882152481969457"
  PUBLIC_CLOUDINARY_API_SECRET: "qs8R00fWS5w2Bnq092vvR7bF3CU"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "dqfh7u7uf"
  DATABASE_URL: "postgresql://neondb_owner:npg_iYjeOcxQsV52@ep-little-truth-a11iznjw-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
  CLERK_SECRET_KEY: k_test_3FGbV4Zl1fUJU11JTtPRMygefzksQEYZL98jCsTVwm
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=: k_test_cGxlYXNpbmctZ3JhY2tsZS0zMS5jbGVyay5hY2NvdW50cy5kZXYk
  # Add other environment variables as needed
handlers:
  - url: /.*
    secure: always
    script: auto




